### ISSUE TITLE
Black screen issue

### ISSUE THREAD

**Issue by narvas** [objcio/issue-13-viper#15]
After adding todo task screen becomes black

iOS 9.3 iPhone 6s

**Comment by chefnobody** [comment]
It likely has something to do with the use of `UIView` animations and `UIViewControllerTransitioningAPI`. Comment out this line and you'll get around the issue with the screen going black. 
https://github.com/objcio/issue-13-viper/blob/master/VIPER%20TODO/Classes/Modules/Add/User%20Interface/Wireframe/VTDAddWireframe.m#L46
